services:
  product-service:
    build:
      context: .
      dockerfile: Dockerfile.local
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://product-db:5432/product_db
      SPRING_DATASOURCE_USERNAME: product_user
      SPRING_DATASOURCE_PASSWORD: product
      SPRING_SERVER_PORT: 8080
    ports:
      - "8090:8080"
    depends_on:
      - product-db

  product-db:
    image: postgres:18
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: product_user
      POSTGRES_PASSWORD: product
    ports:
      - "25432:5432"
