type: Mesh
name: default
meshServices:
  mode: Exclusive # or Everywhere, ReachableBackends, Exclusive
mtls:
  enabledBackend: ca-1
  backends:
    - name: ca-1
      type: builtin
      dpCert:
        rotation:
          expiration: 1d
      conf:
        caCert:
          RSAbits: 2048
          expiration: 10y
